# Generated by Django 5.0.6 on 2024-05-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('birthplace', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField())
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
    

