# Generated by Django 5.0.6 on 2024-05-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information','0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
