# Generated by Django 5.0.6 on 2024-05-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_add_phone_number'),
        ('information', '0003_alter_users_image'),
    ]

    operations = [
    ]
